services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: nit37
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build: .
    ports:
      - "6000:6000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: nit37
    depends_on:
      - mysql
